config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'
  root 'sessions#age'
  get '/home', to: 'sessions#home'


  resources :portfolios
  resources :ingredients
  resources :recipe_ingredients
  resources :recipes
  resources :recipes do
    resources :portfolios, shallow: true
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :portfolios, dependent: :destroy
    has_many :users, through: :portfolios
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients
    validates :name, uniqueness: true
    validates :ingredients, presence: true
    validates_associated :ingredients

    # accepts_nested_attributes_for :recipe_ingredients
    accepts_nested_attributes_for :ingredients, reject_if: lambda{|attrs| attrs['name'].blank?}

    # def ingredients_attributes=(ingredients_attributes)
    #     ingredients_attributes.values.each do |ingredient_attribute|
    #         ingredient = Ingredient.find_or_create_by(ingredient_attribute)

    #         recipe_ingredient = RecipeIngredient.find_or_create_by(recipe: self, ingredient: ingredient)
    #     end
    # end

    #return the first portfolio object
    def first_create
        self.portfolios.order(:created_at).first
    end

    #return the creator of the recipe
    def creator
        User.find(first_create.user_id)
    end

   
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :ingredient_type, only: [:show, :new, :create, :edit, :update, :destroy]
    before_action :find_ingredients, only: [:new, :new, :create, :edit, :update]

    def index
        @recipes = Recipe.all
    end

    def show
        current_user
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)
            flash[:notice] = 'Recipe was updated.'
            redirect_to @recipe
        else 
            render :edit  
        end
    end

    def new
        # @ingredients = Ingredient.all
        @recipe = Recipe.new
        1.times { @recipe.ingredients.build }
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            current_user.recipes << @recipe
            redirect_to @recipe
        else
            1.times { @recipe.ingredients.build() }
            render :new
        end
    end
    
    def destroy
        @recipe.destroy
        redirect_to recipes_path
    end

    private
    def recipe_params
        params.require(:recipe).permit(:name, :description, ingredient_ids: [], ingredients_attributes: [:id, :name, :description, :ingredient_type])
    end

    def find_recipe
        @recipe = Recipe.find(params[:id])
    end

    def find_ingredients
        @ingredients = Ingredient.all
    end
    
    def ingredient_type
        @ingredient_type = ["alcohol", "mixer", "garnish", "vessel"]
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if recipe.errors.any? %>
    <div class="alert alert-dark" role="alert">
        <ul>
            <% recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>


<div id="recipe-container">

<%= form_with(model: recipe, local: true) do |form| %>

    <%= form.label :Drink_name %> <br>
    <%= form.text_field :name %><br>
    <%= form.label :drink_description %><br>
    <%= form.text_area :description %><br>


<h5>Ingredients</h5>
    <%= form.collection_check_boxes :ingredient_ids, @ingredients, :id, :name%>
    
    <%= form.fields_for :ingredients, recipe.ingredients do |tt|%>
 <h5>Unlisted Ingredient</h5>
        <%= tt.label :name %><br>
        <%= tt.text_field :name %><br>
        <%= tt.label :ingredient_type %><br>
        <%= tt.select :ingredient_type, @ingredient_type %><br>
        <%= tt.label :description %><br>
        <%= tt.text_area :description %><br>         
    <% end %>
        <div class="button-area">
        <%= form.submit :class=> 'btn btn-secondary' %>
<% end %>
    </div>
</div>

app/views/recipes/_ingredient.html.erb
<% if recipe.errors.any? %>
    <div class="alert alert-dark" role="alert">
        <ul>
            <% recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>


<div id="recipe-container">

<%= form_with(model: recipe, local: true) do |form| %>

    <%= form.label :Drink_name %> <br>
    <%= form.text_field :name %><br>
    <%= form.label :drink_description %><br>
    <%= form.text_area :description %><br>


<h5>Ingredients</h5>
    <%= form.collection_check_boxes :ingredient_ids, @ingredients, :id, :name%>

    <div class="button-area">
        <%= form.submit :class=> 'btn btn-secondary' %>
    <% end %>
    </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit <%= @recipe.name %></h1>

<%= render 'ingredient', recipe: @recipe %>

app/views/recipes/index.html.erb
<h1 id="rec-con-title">All Concoctions</h1>


<ul class="mainconcoctions">
<% @recipes.each do |r| %>

<li><%= link_to r.name, recipe_path(r), :id=>"recipe-container-small-card" %></li>
<% end %>
</ul>

<div class="button-area">
<%= link_to "Create a new drink", new_recipe_path, :class=> 'btn btn-secondary' %>
</div>

app/views/recipes/new.html.erb
<h1 id="main-title">Create a Drink</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<div id="recipe-container">

<h1 class="recipe-name"><%=@recipe.name %></h1>

<% if @recipe.creator %>
    <h2 class="creator">created by: <%= link_to @recipe.creator.username, user_path(@recipe.creator) %></h2>
<% end %>

<h2 class="description"><%=@recipe.description %></h2>

<ul class="ingredients-ul">
<h3 class="sub-heading">Ingredients:</h3>
<% @recipe.ingredients.each do |i|%>
    <li class="ingredient-name"><%= i.name %> </li>
    <li class="description"><%= i.ingredient_type %></li>
    <li class="description"><%= i.description %></li>
    </ul>
    </li>
    
                    
<% end %>
</ul>
</div>

<div class="button-area">
<%= link_to "Add to Collection", new_recipe_portfolio_path(@recipe), :class=> 'btn btn-secondary', :id=>"button" %>
<% if @current_user === @recipe.creator %>
<%= link_to "Edit Info", edit_recipe_path(@recipe), :class=> 'btn btn-secondary', :id=>"button"%>
<%= button_to "Delete", @recipe, method: :delete, :class=> 'btn btn-secondary', :id=>"button"%>
<% end %>
</div>