config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'
  root 'sessions#age'
  get '/home', to: 'sessions#home'


  resources :portfolios
  resources :ingredients
  resources :recipe_ingredients
  resources :recipes
  resources :recipes do
    resources :portfolios, shallow: true
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :portfolios, dependent: :destroy
    has_many :recipes, through: :portfolios, dependent: :destroy

    validates :username, presence: true
    validates :password, presence: true
    validates :username, uniqueness: true

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:new, :destroy, :create]

    def index
        @users = User.all
    end
    def show
        current_user
        @recipes = @user.recipes.all
    end

    def edit
    end

    def update
        if @user.update(user_params)
        redirect_to @user
        else 
            render :edit  
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def destroy
        @user.destroy
        
        redirect_to logout_path
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :bio, :favorite_drink)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-dark" role="alert">
        <% @user.errors.full_messages.each do |msg| %>
            <%= msg %>
        <% end %>
    </div>
<% end %>
<div class="login-f">
    <%= form_for @user do |f| %>
        <%= f.label :username %><br>
        <%= f.text_field :username %><br>
        <%= f.label :password %><br>
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %><br>
        <br>
        <i>Optional</i> <br>
        <%= f.label :favorite_drink %><br>
        <%= f.text_field :favorite_drink%><br>
        <%= f.label :bio %><br>
        <%= f.text_area :bio %><br>
        <%= f.submit :class=> 'btn btn-secondary'  %>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1> Edit Account </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div id="recipe-container">
    <br>
    <h2>List of Mixologist</h2><br>
    <ul  class="ingredients-ul">
    <% @users.each do |user| %>
        <li class="ingredient-name"><%= link_to user.username, user_path(user) %></li>
        <li class="description">Bio: <%= user.bio %></li><br>
    <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<h2 id="main-title">Sign Up</h2>

<%= render 'form' %>

<div class="button-area" id="newuserbuttonarea">
<p class="main-tagline"> Have an account?</p>
<%= link_to "Click Here to Log In", login_path, :class=> 'btn btn-secondary' %>
</div>

app/views/users/show.html.erb
<div id="recipe-container">
<br>
<h2><%= @user.username %></h2><br>
<h3>About me: <br><%= @user.bio %></h3><br>
<h3>Favorite Drink: <br><%= @user.favorite_drink %></h3>
    </div>
    <div id="test">
<h4 id="rec-con-title2" ><%= @user.username %>'s libration creations:</h4>
    <ul class="mainconcoctions">
        <% @user.recipes.each do |recipe| %>
            <li><%= link_to recipe.name, recipe_path(recipe), :id=>"recipe-container-small-card"  %></li>
        <% end %>
    </ul>
    </div>
    <div class="button-area">
    <% if @current_user === @user %>
        <%= link_to "Edit Info", edit_user_path(@user), :class=> 'btn btn-secondary' %>
        <%= button_to "Delete", @user, method: :delete, :class=> 'btn btn-secondary' %>
    <% end %>
</div>