config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'
  root 'sessions#age'
  get '/home', to: 'sessions#home'


  resources :portfolios
  resources :ingredients
  resources :recipe_ingredients
  resources :recipes
  resources :recipes do
    resources :portfolios, shallow: true
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    validates :name, uniqueness: true
    # validates :name, presence: true
    validates :description, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    before_action :find_ingredient, only: [:show, :edit, :update, :destroy]
    before_action :ingredient_type, only: [:new, :create, :edit, :update]

    def index
        @ingredients = Ingredient.all
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            redirect_to @ingredient
        else
            render :new
        end
    end

    def edit
    end
    
    def update
        if @ingredient.update(ingredient_params)
            flash[:notice] = "Ingredient Infos have updated!"
            redirect_to @ingredient
        else
            render :new
        end
    end 

    def destroy
        if @ingredient.recipes.count == 0
            @ingredient.destroy
            redirect_to ingredients_path
        else
            flash[:notice] = "Can't delete ingredents that are still in use."
            render :show
        end

    end

    private

    def find_ingredient
        @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
        params.require(:ingredient).permit(:name, :description, :ingredient_type)
    end

    def ingredient_type
        @ingredient_type = ["alcohol","mixer","garnish","vessel"]
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<% if @ingredient.errors.any? %>
    <div class="alert alert-dark" role="alert">
        <ul>
            <% @ingredient.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div id="recipe-container">
    <%= form_for @ingredient do |f|%>
        <%= f.label "Name" %>
        <%= f.text_field :name, :class=>"form-control"%><br>
        <%= f.label "Type" %>
        <%= f.select :ingredient_type, @ingredient_type, :class=>"form-control" %><br><br>
        <%= f.label "Description" %>
        <%= f.text_area :description, :class=>"form-control", :id=>"exampleFormControlTextarea1"%>
        <%= f.submit :class=> 'btn btn-secondary' %>
        <% end %>
</div>

app/views/ingredients/edit.html.erb
<h2>Editing<%= @ingredient.name %></h2>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<div id="recipe-container">
<h1 class="recipe-name"> All Ingredients </h1>
<ul class="ingredients-ul">
    <div> 
        <% @ingredients.each do |i| %>
        <li><%= link_to i.name, ingredient_path(i) %></li>
        <% end %>
    </div>
</ul>
</div>

<div class="button-area">
<%= link_to "Create an Ingredient", new_ingredient_path, :class=> 'btn btn-secondary' %>
</div>

app/views/ingredients/new.html.erb
<%=render 'form'%>

app/views/ingredients/show.html.erb
<div id="recipe-container">
    <h2 class="recipe-name"><%= @ingredient.name %></h2>
    <h3 class="description"><%= @ingredient.ingredient_type %></h3>
    <p class="desciption"><%= @ingredient.description %></p><br>

<h3>Drinks featured: </h3>
<ul class="ingredients-ul">
    <% @ingredient.recipes.each do |recipe| %>
        <li><%= link_to recipe.name , recipe_path(recipe) %></li>
    <% end %>
</ul>
</div>

<div class="button-area">
    <%= link_to "Edit Info", edit_ingredient_path(@ingredient), :class=> 'btn btn-secondary' %>
    <%= button_to "Delete", @ingredient, method: :delete, :class=> 'btn btn-secondary' %>
</div>