config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'
  root 'sessions#age'
  get '/home', to: 'sessions#home'


  resources :portfolios
  resources :ingredients
  resources :recipe_ingredients
  resources :recipes
  resources :recipes do
    resources :portfolios, shallow: true
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouthJuice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="body">
<!------ Nav Bar -------->
<div id="navbar_id">
    <nav class="navbar navbar-expand-md">
    <div class="container-fluid">
    
      <a class="navbar-brand" href="<%= home_path%>">Youth Juice</a>
      <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <% if session[:user_id] %>
            <!-- home  -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= recipes_path %>">Home</a>
          </li>
            <!-- Mixologists  -->
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= users_path %>">Mixologists</a>
          </li>
            <!-- recipe drop down  -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Recipe
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= new_recipe_path %>">Mix a Drink</a></li>
              <li><a class="dropdown-item" href="<%= portfolios_path %>">My Recipes</a></li>
              <li><a class="dropdown-item" href="<%= recipes_path %>">All Recipes</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <!-- ingredient drop down  -->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Ingredients
            </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li> <a class="dropdown-item"  href="<%= ingredients_path %>">Ingredient List</a></li>
              <li><a class="dropdown-item" href="<%= new_ingredient_path %>">Add Ingredient</a></li>
            </ul>
          </li>
            <!-- Account -->
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(session[:user_id]) %>">My Account</a>
          </li>
            <!-- log out  -->

          <li class="nav-item">
            <a class="nav-link" href="<%= logout_path %>">Log Out</a>
          </li>
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-xs-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= home_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= login_path %>">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
    </nav>
    </div>
  </div>
  <% if flash[:notice] %>
    <div class="alert alert-dark" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
    <!------ Body -------->
    <%= yield %>
    <!-- Footer-->

        <footer class="footer">
          <!----<h6 class="footer-text">Colin Schlecht and Kai Peng Li, 2021</h6>--->
        </footer>

        <!-- Bootstrap core JS
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        Third party plugin JS
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
         Core theme JS
        <script src="js/scripts.js"></script>-->
        
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>